sudo: required
services:
 - docker

before_install:
 - docker build -t ankhomenko/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run ankhomenko/react-test npm test -- --coverage

after_success:
 - docker build -t ankhomenko/multi-client ./client
 - docker build -t ankhomenko/multi-nginx ./nginx
 - docker build -t ankhomenko/multi-server ./server
 - docker build -t ankhomenko/multi-worker ./worker
#Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push ankhomenko/multi-client
 - docker push ankhomenko/multi-nginx
 - docker push ankhomenko/multi-server
 - docker push ankhomenko/multi-worker